version: '3.8'
services:
# MONGO DB
  database:
    image: mongo
    container_name: mongodb_local
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=productListUser
      - MONGO_INITDB_ROOT_PASSWORD=productListPassword
    ports:
      - "27017:27017"

# SEED
  database_seed:
    image: seed
    container_name: mongodb_seed
    build:
      context: ./database
    links:
      - database

# BACKEND - API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    container_name: rest_backend
    restart: always
    ports:
      - "3001:3001"
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://database/promotions
      - DB_USER=productListUser
      - DB_PASS=productListPassword
      - PORT=3001
    command: ["npm", "start"]
